name: CI

# Triggers the workflow on pull request events
on:
  pull_request:
    branches: [ main ]  # or master, depending on your default branch

jobs:
  # First job: Lint and Unit Tests
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Unit Tests
      run: npm run test:unit

  # Second job: Run Express app and Integration Tests
  integration:
    needs: unit-test  # This job will run only after 'test' job succeeds
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd example && npm ci

    - name: Start Express App
      run: cd example && npm start &

    - name: Wait for server to start
      run: |
        echo "Waiting for server to start..."
        sleep 10

    - name: Run Integration Tests
      run: npm run test:integration
